/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SweethouseRouteImport } from './routes/sweethouse'
import { Route as SkinsmartRouteImport } from './routes/skinsmart'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as NovabankRouteImport } from './routes/novabank'
import { Route as HomeEntertainmentRouteImport } from './routes/home-entertainment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiAssessmentRouteImport } from './routes/ai-assessment'
import { Route as IndexRouteImport } from './routes/index'

const SweethouseRoute = SweethouseRouteImport.update({
  id: '/sweethouse',
  path: '/sweethouse',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinsmartRoute = SkinsmartRouteImport.update({
  id: '/skinsmart',
  path: '/skinsmart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const NovabankRoute = NovabankRouteImport.update({
  id: '/novabank',
  path: '/novabank',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeEntertainmentRoute = HomeEntertainmentRouteImport.update({
  id: '/home-entertainment',
  path: '/home-entertainment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssessmentRoute = AiAssessmentRouteImport.update({
  id: '/ai-assessment',
  path: '/ai-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assessment': typeof AiAssessmentRoute
  '/contact': typeof ContactRoute
  '/home-entertainment': typeof HomeEntertainmentRoute
  '/novabank': typeof NovabankRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/skinsmart': typeof SkinsmartRoute
  '/sweethouse': typeof SweethouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assessment': typeof AiAssessmentRoute
  '/contact': typeof ContactRoute
  '/home-entertainment': typeof HomeEntertainmentRoute
  '/novabank': typeof NovabankRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/skinsmart': typeof SkinsmartRoute
  '/sweethouse': typeof SweethouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assessment': typeof AiAssessmentRoute
  '/contact': typeof ContactRoute
  '/home-entertainment': typeof HomeEntertainmentRoute
  '/novabank': typeof NovabankRoute
  '/portfolio': typeof PortfolioRoute
  '/projects': typeof ProjectsRoute
  '/skinsmart': typeof SkinsmartRoute
  '/sweethouse': typeof SweethouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assessment'
    | '/contact'
    | '/home-entertainment'
    | '/novabank'
    | '/portfolio'
    | '/projects'
    | '/skinsmart'
    | '/sweethouse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assessment'
    | '/contact'
    | '/home-entertainment'
    | '/novabank'
    | '/portfolio'
    | '/projects'
    | '/skinsmart'
    | '/sweethouse'
  id:
    | '__root__'
    | '/'
    | '/ai-assessment'
    | '/contact'
    | '/home-entertainment'
    | '/novabank'
    | '/portfolio'
    | '/projects'
    | '/skinsmart'
    | '/sweethouse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssessmentRoute: typeof AiAssessmentRoute
  ContactRoute: typeof ContactRoute
  HomeEntertainmentRoute: typeof HomeEntertainmentRoute
  NovabankRoute: typeof NovabankRoute
  PortfolioRoute: typeof PortfolioRoute
  ProjectsRoute: typeof ProjectsRoute
  SkinsmartRoute: typeof SkinsmartRoute
  SweethouseRoute: typeof SweethouseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sweethouse': {
      id: '/sweethouse'
      path: '/sweethouse'
      fullPath: '/sweethouse'
      preLoaderRoute: typeof SweethouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skinsmart': {
      id: '/skinsmart'
      path: '/skinsmart'
      fullPath: '/skinsmart'
      preLoaderRoute: typeof SkinsmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novabank': {
      id: '/novabank'
      path: '/novabank'
      fullPath: '/novabank'
      preLoaderRoute: typeof NovabankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-entertainment': {
      id: '/home-entertainment'
      path: '/home-entertainment'
      fullPath: '/home-entertainment'
      preLoaderRoute: typeof HomeEntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assessment': {
      id: '/ai-assessment'
      path: '/ai-assessment'
      fullPath: '/ai-assessment'
      preLoaderRoute: typeof AiAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssessmentRoute: AiAssessmentRoute,
  ContactRoute: ContactRoute,
  HomeEntertainmentRoute: HomeEntertainmentRoute,
  NovabankRoute: NovabankRoute,
  PortfolioRoute: PortfolioRoute,
  ProjectsRoute: ProjectsRoute,
  SkinsmartRoute: SkinsmartRoute,
  SweethouseRoute: SweethouseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
