import * as SiIcons from "react-icons/si";
import * as DiIcons from "react-icons/di";
import * as HiIcons from "react-icons/hi";

export const SiInstagram = SiIcons.SiInstagram;
export const SiGithub = SiIcons.SiGithub;
export const SiLinkedin = SiIcons.SiLinkedin;
export const SiReact = SiIcons.SiReact;
export const SiTypescript = SiIcons.SiTypescript;
export const SiTailwindcss = SiIcons.SiTailwindcss;
export const SiDocker = SiIcons.SiDocker;
export const SiPostgresql = SiIcons.SiPostgresql;
export const SiPython = SiIcons.SiPython;
export const SiFigma = SiIcons.SiFigma;
export const SiVercel = SiIcons.SiVercel;
export const SiHtml5 = SiIcons.SiHtml5;
export const SiAmazon = SiIcons.SiAmazon;
export const SiGooglecloud = SiIcons.SiGooglecloud;
export const SiCss3 = SiIcons.SiCss3;
export const DiGit = DiIcons.DiGit;
export const SiVite = SiIcons.SiVite;
export const SiSpringboot = SiIcons.SiSpringboot;
export const SiApachekafka = SiIcons.SiApachekafka;
export const SiKubernetes = SiIcons.SiKubernetes;
export const SiCloudflare = SiIcons.SiCloudflare;
export const SiVitest = SiIcons.SiVitest;
export const SiOpenai = SiIcons.SiOpenai;
export const SiAdobephotoshop = SiIcons.SiAdobephotoshop;

export const DiJavascript = DiIcons.DiJavascript;
export const DiJava = DiIcons.DiJava;
export const HiOutlineMail = HiIcons.HiOutlineMail;
